name: CI

on:
  push:
    branches:
      - main
      - 'temp/**'
      - 'feature/*'
      - 'bugfix/*'
  pull_request:
    branches:
      - main
      - 'temp/**'
      - 'feature/*'
      - 'bugfix/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev extras
        run: |
          pip install .[dev]

      - name: Run Tox
        run: tox
